### ISSUE TITLE
software stops after few seconds

### ISSUE THREAD

**Issue by MeHelmy** [Nextomics/nextsv#6]
Hi,
knowing that I am running on personal PC using Ubuntu 16.

I am running the tools as suggested from documentation 

perl  ~/source/nextsv/nextsv.pl 245.config

but it write out those two line

> Generating scripts for BLASR/PBHoney...
> Generating scripts for ngmlr/Sniffles...

and then nothing happens.
no errors, no results

so I think I need to run each sh file in each folder right?

also while I was reading the paper there was no mention for duplication! 
is the pipeline do not deal with duplication? even though Sniffles detect both duplication and inverted duplication.

**Comment by fangli80** [comment]
Hi, please run the sh file generated by NextSV. You can either run them directly or submit them to the cluster. The paper did not evaluate the performance of duplication detection because we currently do not have gold standard duplication data set. However, NextSV supports duplication detection though the paper did not discuss it.  You can find the duplication calls in the Sniffles results. In addition, duplication can be viewed as a special kind of insertion, of which the inserted sequence is the same. You may also check the insertion calls of PBHoney.

**Comment by MeHelmy** [comment]
I am running on slrum, but the code supported by the tool uses qsub (so I think the way is to run them directly).

regarding duplication I understand now why it was not mentioned.

**Comment by fangli80** [comment]
OK. Please let me know if you have any other questions.
